"""Article Writer service — generate a draft section by section (PRD §7, FR-7.2/7.5).

The writer turns an approved Outline (H1/H2/H3 ``nodes`` tree, PRD §6/§9.6) into a
draft: one Markdown section per H2/H3 node. Each section is generated by an LLM
seat via :func:`app.providers.get_adapter`; with no API key configured the factory
returns a deterministic :class:`~app.providers.base.MockAdapter`, so every function
here must still produce a sensible result. To guarantee that, each LLM call has a
deterministic NON-LLM fallback: the adapter text is parsed defensively
(``json.loads`` in a try/except) and, failing that, a heuristic emits placeholder
prose derived purely from the outline node + brief.

Service functions are PURE (outline/brief dicts -> dataclasses/dicts) so they are
unit-testable without a DB or any provider keys. DB persistence (Draft versioning)
lives in the router (PRD §14: ``draft`` table).
"""

from __future__ import annotations

import json
import queue
import re
from collections.abc import Iterator
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field

from app.compliance.autofix import autofix_text
from app.outline.service import is_directive_heading
from app.providers import ProviderError, ProviderRefusal, get_adapter

# Roughly the number of words the heuristic fallback emits per body section, kept
# small but non-trivial so ``word_count`` is always > 0 even with the mock adapter.
_FALLBACK_BODY_SENTENCES = 3

# How many sections stream concurrently. Bounded so we don't hammer the provider
# or flood the SSE channel, while still writing the article far faster than one
# section at a time (FR-7.2).
_MAX_SECTION_WORKERS = 4


SYSTEM_PROMPT = (
    "You are an expert practitioner writing ONE section of a long-form article "
    "that must beat the pages currently ranking on Google page one AND be worth "
    "quoting by AI engines (ChatGPT, Perplexity, Google AI Overviews). You write "
    "from real expertise, not summary.\n"
    "TOPIC: the heading names a reader-facing subject. Write ABOUT that subject "
    "for the reader. NEVER restate the heading as an instruction and NEVER write "
    "meta-commentary about SEO, structure, entities, schema, E-E-A-T, keywords or "
    "'this guide'. Write the actual subject content a reader came for.\n"
    "ANSWER-FIRST: the FIRST sentence must directly address the heading with a "
    "concrete, useful statement. A reader (or an AI engine quoting only that "
    "sentence) must learn something immediately. No warm-up sentences, no "
    "restating the question.\n"
    "EXPERIENCE (E-E-A-T): write like someone who has actually used, tested or "
    "done this: practical observations ('in practice...', 'you'll notice...'), "
    "tradeoffs, mistakes to avoid, who it is NOT for. Give real cons, not "
    "marketing. Never over-promise.\n"
    "SPECIFICITY: concrete names, figures, steps and scenarios. One vivid "
    "specific beats three generalities. Cut every sentence that adds no new "
    "information.\n"
    "HUMAN RHYTHM: vary sentence length hard — some under 7 words, some long. "
    "Use contractions. Active voice. Address the reader as 'you' where natural; "
    "the editorial voice is 'we'. Never start consecutive sentences the same way.\n"
    "FORMAT FOR SCANNERS: when enumerating 3+ parallel items, use a Markdown "
    "bulleted or numbered list. When comparing options/plans/numbers, use a "
    "compact Markdown table — and name the source of the table's figures in the "
    "sentence that introduces it (e.g. 'specs per Wirecutter'). Bold at most ONE "
    "key phrase per section. Keep prose paragraphs to 2-4 sentences. Never write "
    "a wall of text.\n"
    "BANNED phrases (they read as generic AI copy, never use any): 'in "
    "conclusion', 'it's important to note', 'in today's world', 'when it comes "
    "to', 'a wide range of', 'plays a crucial role', 'navigating the', 'in the "
    "realm of', 'delve', 'unlock', 'elevate', 'game-changer', 'moreover', "
    "'furthermore'. Never use em-dashes; use commas or periods.\n"
    "SOURCING — the iron rule: every figure (statistic, price, spec, capacity, "
    "percentage) MUST come from the 'VERIFIED FACTS' list when one is provided "
    "for this section, cited to the source given there. A number that is not in "
    "the facts list DOES NOT EXIST for you — from memory you may write only "
    "qualitative statements (ranges and tradeoffs in words). Attribute inline "
    "('according to Wirecutter', 'per Tom's Guide') and VARY which source you "
    "cite — never the same source on consecutive claims. Copy every source "
    "name/domain CHARACTER FOR CHARACTER (no respellings); a source not listed "
    "does not exist. When neither facts nor sources are supplied, write "
    "QUALITATIVELY: no figures, no 'studies show', no unsupported superlatives. "
    "Never invent statistics.\n"
    "SEO: weave the assigned keyword for this section in ONCE, naturally (never "
    "force or repeat it); mention listed entities only where they genuinely fit.\n"
    "Return ONLY the body for this section (no heading line). If you reply as JSON, "
    "use the shape {\"markdown\": str}."
)


# --------------------------------------------------------------------------- #
# Result shapes (pure data; JSON-serialisable for the Draft.sections column)
# --------------------------------------------------------------------------- #
@dataclass
class Section:
    """One rendered article section (maps onto an outline H2/H3 node)."""

    heading: str
    level: int
    markdown: str

    def word_count(self) -> int:
        return _count_words(self.markdown)


@dataclass
class DraftResult:
    """Full draft: ordered sections plus the total body word count (PRD §7)."""

    sections: list[Section] = field(default_factory=list)
    word_count: int = 0

    def as_dict(self) -> dict:
        return {
            "sections": [asdict(s) for s in self.sections],
            "word_count": self.word_count,
        }


# --------------------------------------------------------------------------- #
# Outline parsing (defensive — the Outline Builder is a sibling module; accept
# the common node shapes rather than assuming one schema)
# --------------------------------------------------------------------------- #
def _node_heading(node: dict) -> str:
    """Best-effort heading text for an outline node."""
    for key in ("heading", "title", "text", "name", "label"):
        value = node.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return "Section"


def _node_level(node: dict) -> int:
    """Best-effort heading level for an outline node.

    Accepts ``level`` as an int (1-6) or a tag string ("h1".."h6"). H1 (level 1)
    is preserved so :func:`_flatten_nodes` can skip the article title; H2/H3 are
    body sections. Unknown shapes default to 2 (a body section). Levels above 3
    clamp to 3 so deep nesting still renders.
    """
    raw = node.get("level", node.get("h", node.get("tag")))
    if isinstance(raw, bool):  # bool is an int subclass — guard first
        return 2
    if isinstance(raw, int):
        if raw <= 1:
            return 1
        return raw if raw in (2, 3) else 3
    if isinstance(raw, str):
        match = re.search(r"([1-6])", raw)
        if match:
            level = int(match.group(1))
            return level if level <= 3 else 3
    return 2


def _children(node: dict) -> list[dict]:
    children = node.get("children", node.get("nodes", node.get("subsections")))
    return [c for c in children if isinstance(c, dict)] if isinstance(children, list) else []


def _flatten_nodes(nodes: list) -> list[dict]:
    """Flatten an outline tree into the ordered list of writable sections.

    Skips the H1 (level < 2): the article title is not a body section. Each
    surviving node is yielded with a resolved ``heading`` and ``level``, parents
    before their children (depth-first), preserving outline order (FR-7.2).
    """
    flat: list[dict] = []

    def walk(items: list) -> None:
        for item in items:
            if not isinstance(item, dict):
                continue
            heading = _node_heading(item)
            level = _node_level(item)
            kids = _children(item)
            # Final guard: an editorial/SEO directive must never become a section
            # heading (else the writer produces meta-commentary executing it). If
            # every node were filtered, _extract_sections backstops with "Overview".
            if level >= 2 and not is_directive_heading(heading):
                flat.append({"heading": heading, "level": level, "node": item})
            # A FAQ section writes its own Q&A from the research questions; don't
            # ALSO flatten its question children into standalone body sections
            # (that duplicated every question as a long section in the draft).
            if _section_kind(heading) == "faq":
                continue
            walk(kids)

    walk(nodes if isinstance(nodes, list) else [])
    return flat


def _extract_sections(outline: dict) -> list[dict]:
    """Return the ordered writable sections from an outline dict.

    Looks at ``outline['nodes']`` (the ORM/JSON column, PRD §14) first, then a
    bare list, then a ``sections`` key — so callers can pass either an Outline row
    payload or a hand-built dict in tests.
    """
    if isinstance(outline, dict):
        nodes = outline.get("nodes")
        if not isinstance(nodes, list):
            nodes = outline.get("sections")
    elif isinstance(outline, list):
        nodes = outline
    else:
        nodes = None
    sections = _flatten_nodes(nodes if isinstance(nodes, list) else [])
    if sections:
        # The Quick-Verdict answer block must LEAD the article (AEO/GEO): if the
        # outline tree nested the body sections under the H1, a top-level verdict
        # sibling flattens after them — force it to the front regardless.
        for i, section in enumerate(sections):
            if _section_kind(section["heading"]) == "verdict":
                if i > 0:
                    sections.insert(0, sections.pop(i))
                break
        return sections
    # No usable outline — emit a single default body section so the writer still
    # produces a non-empty draft (mock-friendly).
    return [{"heading": "Overview", "level": 2, "node": {}}]


# --------------------------------------------------------------------------- #
# Word counting + prompt building
# --------------------------------------------------------------------------- #
def _count_words(markdown: str) -> int:
    """Count words in body Markdown, ignoring heading marker lines."""
    words = 0
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        words += len(re.findall(r"\b\w+\b", stripped))
    return words


def _brief_summary(brief: dict) -> str:
    lines = [
        f"Topic: {brief.get('topic', '')}",
        f"Primary keyword: {brief.get('keyword', '')}",
        f"Country: {brief.get('country', 'US')}",
        f"Audience: {brief.get('audience') or 'general readers'}",
        f"Tone: {brief.get('tone') or 'neutral, balanced'}",
        f"Goal: {brief.get('goal') or 'rank on search and be cited by AI engines'}",
    ]
    atype = (brief.get("article_type") or "").strip()
    if atype:
        lines.append(
            f"Article format: {atype} — structure and depth this section to fit a {atype}."
        )
    words = brief.get("word_count")
    if isinstance(words, int) and words > 0:
        lines.append(
            f"Target total length: about {words} words across the whole article; "
            "size this section proportionally to its importance (add depth, never padding)."
        )
    return "\n".join(lines)


def _research_sources_text(research: dict) -> str:
    """Render research sources as a citable list for the writer prompt."""
    out: list[str] = []
    for s in ((research or {}).get("sources") or [])[:6]:
        if isinstance(s, dict):
            title = s.get("title") or s.get("name") or ""
            url = s.get("url") or s.get("link") or s.get("domain") or ""
            label = " — ".join(x for x in (title, url) if x)
        else:
            label = str(s)
        if label:
            out.append(f"- {label}")
    return "\n".join(out) or "- (no external sources supplied — avoid hard statistics)"


def _research_entities_text(research: dict) -> str:
    names: list[str] = []
    for e in ((research or {}).get("entities") or [])[:10]:
        name = e.get("name") or e.get("text") if isinstance(e, dict) else e
        if isinstance(name, str) and name.strip():
            names.append(name.strip())
    return ", ".join(names) or "(none)"


def _research_paa(research: dict) -> list[str]:
    out: list[str] = []
    for q in (research or {}).get("paa") or []:
        if isinstance(q, dict):
            q = q.get("text") or q.get("question")
        if isinstance(q, str) and q.strip():
            out.append(q.strip())
    return out


def _section_kind(heading: str) -> str:
    """Classify a section so the writer can produce answer-engine-ready blocks."""
    h = heading.lower()
    if any(w in h for w in ("quick verdict", "verdict", "tl;dr", "bottom line", "key takeaway")):
        return "verdict"
    if any(w in h for w in ("faq", "frequently asked", "questions people", "common questions")):
        return "faq"
    return "body"


def _feedback_line(feedback: str | None) -> str:
    """Render an optional editor instruction appended to a section prompt."""
    fb = (feedback or "").strip()
    if not fb:
        return ""
    return (
        f"\n\nEDITOR FEEDBACK (the previous version of this section was rejected "
        f"for this; rewrite to address it): {fb[:1000]}"
    )


# --------------------------------------------------------------------------- #
# Per-section context: keyword assignment, outline elements, competitor coverage
# --------------------------------------------------------------------------- #
_CTX_STOP = frozenset(
    {"the", "a", "an", "and", "or", "for", "to", "of", "in", "on", "is", "are",
     "with", "how", "what", "why", "your", "you", "vs", "best", "top"}
)


def _ctx_tokens(text: str) -> set[str]:
    return {
        t for t in re.findall(r"[a-z0-9]+", str(text).lower())
        if len(t) >= 3 and t not in _CTX_STOP
    }


def _keyword_assignments(sections: list[dict], research: dict) -> list[str | None]:
    """Assign one keyword per section: primary to the first body section,
    secondaries rotated across the rest. Verdict/FAQ sections get none (their
    format carries keywords naturally)."""
    kw = (research or {}).get("keywords") or {}
    primary = kw.get("primary") or ""
    secondary = [s for s in kw.get("secondary") or [] if isinstance(s, str)]
    plan: list[str | None] = []
    body_seen = 0
    sec_i = 0
    for sec in sections:
        if _section_kind(sec.get("heading", "")) != "body":
            plan.append(None)
            continue
        body_seen += 1
        if body_seen == 1 and primary:
            plan.append(primary)
        elif secondary:
            plan.append(secondary[sec_i % len(secondary)])
            sec_i += 1
        else:
            plan.append(primary or None)
    return plan


def _element_notes(outline: dict) -> dict[str, list[str]]:
    """Map outline element placements (table/faq/answer_block/...) to their
    section heading (lower-cased) so the writer executes them in-body."""
    notes: dict[str, list[str]] = {}
    for el in (outline or {}).get("elements") or []:
        if not isinstance(el, dict):
            continue
        section = str(el.get("section") or "").strip().lower()
        etype = str(el.get("type") or "").strip()
        if not section or not etype:
            continue
        note = str(el.get("note") or "").strip()
        label = {"answer_block": "direct answer block", "cta": "call to action"}.get(
            etype, etype.replace("_", " ")
        )
        notes.setdefault(section, []).append(f"{label}" + (f" — {note}" if note else ""))
    return notes


def _competitor_context(heading: str, research: dict, cap: int = 3) -> str:
    """What the ranking pages cover under headings similar to this one.

    Token-overlap match against the fetched competitor pages; gives the writer
    the coverage bar to clear ('cover this, then go deeper or differ').
    """
    target = _ctx_tokens(heading)
    if not target:
        return ""
    hits: list[tuple[float, str]] = []
    for page in (research or {}).get("competitors") or []:
        if not isinstance(page, dict):
            continue
        domain = page.get("domain") or "a ranking page"
        for comp_heading in page.get("headings") or []:
            toks = _ctx_tokens(comp_heading)
            if not toks:
                continue
            overlap = len(target & toks) / len(target)
            if overlap >= 0.4:
                hits.append((overlap, f"\"{comp_heading}\" ({domain})"))
    if not hits:
        return ""
    hits.sort(key=lambda x: -x[0])
    seen: set[str] = set()
    top: list[str] = []
    for _, label in hits:
        if label in seen:
            continue
        seen.add(label)
        top.append(label)
        if len(top) >= cap:
            break
    return "; ".join(top)


def _section_prompt(
    section: dict,
    brief: dict,
    all_headings: list[str],
    research: dict,
    feedback: str | None = None,
    extra: dict | None = None,
) -> str:
    heading = section["heading"]
    level = section["level"]
    kind = _section_kind(heading)
    extra = extra or {}
    context = (
        f"{_brief_summary(brief)}\n\n"
        f"Research sources you may cite:\n{_research_sources_text(research)}\n\n"
        f"Key entities to mention: {_research_entities_text(research)}\n"
        f"Full outline headings: {json.dumps(all_headings)}\n"
    )
    if extra.get("keyword"):
        context += f"Assigned keyword for this section (weave in once): {extra['keyword']}\n"
    if extra.get("facts"):
        lines = "\n".join(
            f"- {f['text']} [source: {f['source']}]" for f in extra["facts"]
        )
        context += (
            "VERIFIED FACTS for this section — the ONLY figures you may state, "
            "each cited to its source:\n" + lines + "\n"
        )
    if extra.get("evidence_notes"):
        context += extra["evidence_notes"] + "\n"
    if extra.get("competitor_context"):
        context += (
            "What ranking pages cover under similar headings: "
            f"{extra['competitor_context']}\n"
            "Clear that coverage bar, then go one level deeper or add what they miss "
            "(never copy their phrasing).\n"
        )
    if extra.get("elements"):
        context += (
            "This section MUST include: " + "; ".join(extra["elements"]) + ".\n"
        )
    if extra.get("word_budget"):
        context += (
            f"LENGTH for this section: about {extra['word_budget']} words (hard "
            "guidance). Depth within the budget; cutting a weak point beats "
            "padding a strong one.\n"
        )
    tail = _feedback_line(feedback)

    if kind == "verdict":
        return context + (
            "\nWrite a 'Quick Verdict': a direct, snippet-ready answer of 40 to 60 "
            "words to the primary query. Start the first sentence with 'Quick "
            "verdict:'. Be specific and balanced (a real recommendation, not "
            "hedging). Name a specific option ONLY if it appears in the research "
            "data above (sources/entities/SERP) — never recommend a product or "
            "brand the research does not mention."
        ) + tail
    if kind == "faq":
        questions = _research_paa(research)
        if questions:
            joined = "\n".join(f"- {q}" for q in questions[:6])
            return context + (
                "\nWrite an FAQ section. Answer each question below in 1 to 2 "
                "sentences, citing a listed source only if one directly supports "
                "the answer. If a question is awkwardly phrased, rewrite it into "
                "natural, grammatical English before answering. Format each item as "
                f"'**<question>**' on its own line, then the answer.\nQuestions:\n{joined}"
            ) + tail
        subject = brief.get("topic") or brief.get("keyword") or "the topic"
        return context + (
            "\nWrite an FAQ section with 4 to 6 natural 'People Also Ask' style "
            f"questions a reader would search about {subject}, then answer each in 1 "
            "to 2 sentences. Phrase every question in correct, grammatical English "
            "(never treat the keyword phrase as a singular product name). Format each "
            "as '**<question>**' on its own line, then the answer on the next line."
        ) + tail
    opener_note = (
        "\nThis is the OPENING body section: hook the reader with the core "
        "answer/promise in the first two sentences and make them trust the rest "
        "of the article."
        if extra.get("is_opening")
        else ""
    )
    return context + (
        f"\nWrite the body for this reader-facing section only, 2 to 4 tight "
        f"paragraphs about the topic (not about SEO or how the article is built), "
        f"using a list or table where the content calls for one.{opener_note}\n"
        f"Section heading (H{level}): {heading}\n"
        "If sources are listed above, attribute each factual, numeric or comparative "
        "claim to a named source (vary the source across claims). If none are listed, "
        "keep claims qualitative — no unattributed figures or superlatives."
    ) + tail


# --------------------------------------------------------------------------- #
# Fallback prose (deterministic, zero-LLM)
# --------------------------------------------------------------------------- #
def _fallback_markdown(section: dict, brief: dict) -> str:
    """Deterministic placeholder prose for a section when no LLM text is usable.

    Derived purely from the heading + brief so the draft is coherent and the word
    count is always positive, satisfying the zero-API-key contract.
    """
    heading = section["heading"]
    topic = brief.get("topic") or brief.get("keyword") or "this topic"
    keyword = brief.get("keyword") or topic
    audience = brief.get("audience") or "readers"
    sentences = [
        f"This section covers {heading.lower()} in the context of {topic}.",
        f"It gives {audience} a clear, sourced view of {keyword} without "
        f"over-promising.",
        f"Replace this placeholder with the final, fact-checked draft for "
        f"\"{heading}\".",
    ]
    return " ".join(sentences[:_FALLBACK_BODY_SENTENCES])


def _parse_adapter_markdown(text: str) -> str:
    """Pull body Markdown out of an adapter response, defensively.

    Accepts either a JSON object ({"markdown": ...} / {"text": ...}) or raw text.
    Returns a stripped string; the caller decides whether it is usable.
    """
    text = (text or "").strip()
    if not text:
        return ""
    if text.startswith("{") or text.startswith("["):
        try:
            data = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            data = None
        if isinstance(data, dict):
            for key in ("markdown", "text", "body", "content"):
                value = data.get(key)
                if isinstance(value, str) and value.strip():
                    return _strip_code_fence(value.strip())
    return _strip_code_fence(text)


def _strip_code_fence(text: str) -> str:
    """Remove an accidental ```lang ... ``` wrapper some models put around prose."""
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z0-9]*\s*\n?", "", text)
        text = re.sub(r"\n?```\s*$", "", text)
    return text.strip()


def _section_extras(
    parsed: list[dict], outline: dict, research: dict, brief: dict | None = None
) -> list[dict]:
    """Precompute each section's context pack: assigned keyword, verified facts,
    outline element placements, competitor coverage, opening flag, word budget."""
    from app.research.evidence import facts_for_heading

    keywords = _keyword_assignments(parsed, research)
    notes = _element_notes(outline if isinstance(outline, dict) else {})
    evidence = (research or {}).get("facts") or {}
    primary_kw = ((research or {}).get("keywords") or {}).get("primary") or ""
    # Consensus/disagreement synthesis: original editorial insight no single
    # competitor page has — offered to the opening + comparison-ish sections.
    synth_lines: list[str] = []
    for point in (evidence.get("consensus") or [])[:3]:
        synth_lines.append(f"- Reviewers agree: {point}")
    for point in (evidence.get("disagreements") or [])[:3]:
        synth_lines.append(f"- Sources disagree: {point}")
    evidence_notes = (
        "Cross-source synthesis you may draw on (name the sources as given):\n"
        + "\n".join(synth_lines)
        if synth_lines
        else ""
    )

    # Per-section word budget: without it, a many-section outline overshoots the
    # target 2-3x (an LLM never does the division itself). Verdict/FAQ have
    # their own formats; body sections split the target evenly, clamped sane.
    target = (brief or {}).get("word_count")
    n_body = sum(1 for s in parsed if _section_kind(s.get("heading", "")) == "body")
    budget: int | None = None
    if isinstance(target, int) and target > 0 and n_body > 0:
        budget = max(90, min(380, round(target * 0.85 / n_body)))

    extras: list[dict] = []
    opening_marked = False
    for i, section in enumerate(parsed):
        heading = section.get("heading", "")
        kind = _section_kind(heading)
        is_body = kind == "body"
        is_opening = is_body and not opening_marked
        extra = {
            "keyword": keywords[i],
            "elements": notes.get(heading.strip().lower()) or [],
            "competitor_context": _competitor_context(heading, research),
            "is_opening": is_opening,
            "word_budget": budget if is_body else None,
            # Verified facts matched to this heading (verdict/FAQ get a wider
            # pull so their answers are grounded too).
            "facts": facts_for_heading(
                evidence, heading, primary_kw, cap=6 if kind != "body" else 5
            ),
            "evidence_notes": evidence_notes if (is_opening or kind == "verdict") else "",
        }
        if is_body:
            opening_marked = True
        extras.append(extra)
    return extras


def _write_section_body(
    section: dict,
    brief: dict,
    all_headings: list[str],
    provider: str,
    research: dict,
    feedback: str | None = None,
    extra: dict | None = None,
) -> str:
    """Generate one section's body via the adapter, with a heuristic fallback.

    Never raises: provider refusal/transport errors degrade to the deterministic
    fallback so a single failed seat cannot break the whole draft (FR-7.2).
    """
    prompt = _section_prompt(section, brief, all_headings, research, feedback, extra)
    try:
        resp = get_adapter(provider).complete(
            system=SYSTEM_PROMPT, prompt=prompt, json_mode=False
        )
    except (ProviderRefusal, ProviderError):
        return _fallback_markdown(section, brief)

    body = _parse_adapter_markdown(resp.text)
    # The mock adapter returns a short non-JSON line; that is fine as body text,
    # but if parsing yields nothing usable, fall back to deterministic prose.
    if _count_words(body) == 0:
        return _fallback_markdown(section, brief)
    return body


def _render_section(
    section: dict,
    brief: dict,
    all_headings: list[str],
    provider: str,
    research: dict,
    feedback: str | None = None,
    extra: dict | None = None,
) -> Section:
    body = autofix_text(
        _write_section_body(
            section, brief, all_headings, provider, research, feedback, extra
        )
    )
    return Section(heading=section["heading"], level=section["level"], markdown=body)


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def generate_draft(
    outline: dict,
    brief: dict,
    *,
    provider: str = "anthropic",
    research: dict | None = None,
    feedback: str | None = None,
) -> dict:
    """Generate a full draft section by section from an outline (FR-7.2).

    Args:
        outline: Outline payload — an Outline row's ``nodes``/``sections`` tree or
            a bare list of nodes. H2/H3 nodes become body sections (H1 is skipped).
        brief: Project brief (topic/keyword/country/audience/tone/goal).
        provider: Council seat provider name resolved via ``get_adapter``.
        feedback: Optional editor instruction for a review-mode regenerate; woven
            into every section's prompt.

    Returns:
        ``{"sections": [{"heading", "level", "markdown"}, ...], "word_count": int}``
        — JSON-serialisable for the ``draft.sections`` column. ``word_count`` is the
        summed body word count and is always > 0.
    """
    research = research or {}
    parsed = _extract_sections(outline)
    all_headings = [s["heading"] for s in parsed]
    extras = _section_extras(parsed, outline if isinstance(outline, dict) else {}, research, brief)
    rendered = [
        _render_section(s, brief, all_headings, provider, research, feedback, extras[i])
        for i, s in enumerate(parsed)
    ]
    total = sum(s.word_count() for s in rendered)
    return DraftResult(sections=rendered, word_count=total).as_dict()


def _stream_section_body(
    section: dict,
    brief: dict,
    all_headings: list[str],
    provider: str,
    research: dict,
    extra: dict | None = None,
) -> Iterator[dict]:
    """Yield ``{"kind": "delta", "delta": str}`` token chunks for one section body.

    Never raises: a provider refusal/transport error just ends the stream (the
    caller then emits deterministic fallback prose), mirroring the safety contract
    of :func:`_write_section_body` (FR-7.2).
    """
    prompt = _section_prompt(section, brief, all_headings, research, None, extra)
    try:
        stream = get_adapter(provider).stream(
            system=SYSTEM_PROMPT, prompt=prompt, json_mode=False
        )
        for ev in stream:
            if ev.response is not None:
                continue
            if ev.delta:
                yield {"kind": "delta", "delta": ev.delta}
    except (ProviderRefusal, ProviderError):
        return


def stream_draft(
    outline: dict, brief: dict, *, provider: str = "anthropic", research: dict | None = None
) -> Iterator[dict]:
    """Generate a draft section-by-section, streaming tokens live (FR-7.2, §16).

    Sections are written CONCURRENTLY (bounded by :data:`_MAX_SECTION_WORKERS`),
    each streaming into its own slot, so the reader watches the whole article
    fill in at once instead of waiting for one blocking call. Yields:

        {"kind": "section_start", "index", "heading", "level"}
        {"kind": "section_delta", "index", "delta"}                 # a token, live
        {"kind": "section_done",  "index", "heading", "level", "markdown"}
        {"kind": "done", "draft": {"sections": [...], "word_count": int}}  # terminal

    ``section_done.markdown`` is the canonical, JSON-cleaned body — consumers
    should replace (not append) the live text with it. Falls back to deterministic
    prose per section when a seat yields nothing, so the draft is always non-empty
    (zero-API-key contract). Never raises per section: a failed section degrades to
    fallback prose rather than hanging or crashing the draft.
    """
    research = research or {}
    parsed = _extract_sections(outline)
    all_headings = [s["heading"] for s in parsed]
    extras = _section_extras(parsed, outline if isinstance(outline, dict) else {}, research, brief)
    n = len(parsed)
    results: list[Section | None] = [None] * n
    sink: queue.Queue = queue.Queue()

    def worker(index: int, section: dict) -> None:
        acc: list[str] = []
        sink.put({
            "kind": "section_start",
            "index": index,
            "heading": section["heading"],
            "level": section["level"],
        })
        try:
            try:
                for ev in _stream_section_body(
                    section, brief, all_headings, provider, research, extras[index]
                ):
                    acc.append(ev["delta"])
                    sink.put({"kind": "section_delta", "index": index, "delta": ev["delta"]})
                body = _parse_adapter_markdown("".join(acc))
                if _count_words(body) == 0:
                    body = _fallback_markdown(section, brief)
            except Exception:  # noqa: BLE001 - degrade a failed section, never hang
                body = _fallback_markdown(section, brief)
            # Auto-remediate mechanical house-rule triggers (em-dashes, first-person)
            # so the canonical body sent downstream is already publish-clean (PRD §11).
            body = autofix_text(body)
            sec = Section(heading=section["heading"], level=section["level"], markdown=body)
            results[index] = sec
            sink.put({
                "kind": "section_done",
                "index": index,
                "heading": sec.heading,
                "level": sec.level,
                "markdown": sec.markdown,
            })
        finally:
            # Always emitted, even if autofix/Section construction raises, so the
            # consumer's countdown completes and the stream can never hang.
            sink.put({"kind": "__worker_done__"})

    with ThreadPoolExecutor(max_workers=min(_MAX_SECTION_WORKERS, max(1, n))) as pool:
        for i, section in enumerate(parsed):
            pool.submit(worker, i, section)
        remaining = n
        while remaining > 0:
            item = sink.get()
            if item["kind"] == "__worker_done__":
                remaining -= 1
                continue
            yield item

    sections = [s for s in results if s is not None]
    total = sum(s.word_count() for s in sections)
    yield {
        "kind": "done",
        "draft": DraftResult(sections=sections, word_count=total).as_dict(),
    }


def regenerate_section(
    outline: dict,
    brief: dict,
    section_index: int,
    *,
    provider: str = "anthropic",
    research: dict | None = None,
    feedback: str | None = None,
) -> dict:
    """Regenerate a single section of the draft (FR-7.5).

    Args:
        outline: Same outline payload accepted by :func:`generate_draft`.
        brief: Project brief.
        section_index: Zero-based index into the flattened H2/H3 section list.
        provider: Council seat provider name.
        feedback: Optional editor instruction steering the rewrite of this section.

    Returns:
        ``{"heading", "level", "markdown"}`` for the regenerated section.

    Raises:
        IndexError: if ``section_index`` is out of range for the outline.
    """
    research = research or {}
    parsed = _extract_sections(outline)
    if section_index < 0 or section_index >= len(parsed):
        raise IndexError(
            f"section_index {section_index} out of range (0..{len(parsed) - 1})"
        )
    all_headings = [s["heading"] for s in parsed]
    extras = _section_extras(parsed, outline if isinstance(outline, dict) else {}, research, brief)
    section = _render_section(
        parsed[section_index],
        brief,
        all_headings,
        provider,
        research,
        feedback,
        extras[section_index],
    )
    return asdict(section)


# --------------------------------------------------------------------------- #
# Proofreading (copy-edit pass, PRD §7 editable draft)
# --------------------------------------------------------------------------- #
PROOFREAD_SYSTEM = (
    "You are a meticulous copy editor. Correct grammar, spelling, punctuation, "
    "clarity and flow WITHOUT changing meaning, facts, numbers, structure or "
    "Markdown. Keep roughly the same length. Rewrite first-person singular "
    "('I'/'my') to the editorial 'we', and never use em-dashes. Do not add new "
    "claims or remove citations. Return ONLY the corrected Markdown body (no "
    "preamble). If you reply as JSON, use the shape {\"markdown\": str}."
)


def _proofread_one(section: dict, provider: str) -> dict:
    """Copy-edit one section; conservative — keeps the original if unsure.

    Falls back to the original body on provider error, on mock output, or if the
    edit looks destructive (lost more than half the words), so proofreading can
    never gut the draft (and is a safe no-op with zero keys).
    """
    body = section.get("markdown") or ""
    heading = section.get("heading", "")
    level = section.get("level", 2)
    if not body.strip():
        return {"heading": heading, "level": level, "markdown": body}
    try:
        resp = get_adapter(provider).complete(
            system=PROOFREAD_SYSTEM, prompt=body, json_mode=False
        )
        fixed = _parse_adapter_markdown(resp.text)
    except (ProviderRefusal, ProviderError):
        fixed = ""
    if (
        not fixed
        or "[mock:" in fixed
        or _count_words(fixed) < 0.5 * max(1, _count_words(body))
    ):
        fixed = body
    return {"heading": heading, "level": level, "markdown": autofix_text(fixed)}


def proofread_sections(sections: list[dict], *, provider: str = "anthropic") -> list[dict]:
    """Copy-edit every section concurrently, preserving order (FR-7.1)."""
    items = [dict(s) for s in (sections or [])]
    if not items:
        return []
    workers = min(_MAX_SECTION_WORKERS, len(items))
    with ThreadPoolExecutor(max_workers=workers) as pool:
        return list(pool.map(lambda s: _proofread_one(s, provider), items))
