/**
 * Workspaces Service — `04-platform/workspaces.md`.
 *
 * Increment B: provisioning and lifecycle. Invitations, role changes and
 * membership management beyond the first `workspace_admin` are NOT here.
 *
 * ── Atomicity ────────────────────────────────────────────────────────────────
 * Provisioning writes the workspace, the first `workspace_admin` membership,
 * the initial settings layer, the audit record and the outbox event on ONE
 * transaction handle. "Provisioning partially completes → One transaction;
 * impossible" (§"Failure handling").
 *
 * ── Tenant context ───────────────────────────────────────────────────────────
 * `workspaces.id` IS `tenant_id`, and its RLS policy is
 * `WITH CHECK (id = current_setting('app.tenant_id'))`. So the identifier
 * cannot be generated by the INSERT: the transaction has to already be running
 * under the id being inserted. `workspaceId` is therefore an INPUT, and the
 * caller opens the transaction with
 * `withTenant({ tenantId: workspaceId, organizationId })`.
 *
 * Obtain one from the database's own generator — `SELECT uuidv7()` (migration
 * 0001) — rather than a v4: v7 is time-ordered, so B-tree insertion stays
 * sequential, and `gen_random_uuid()` would silently discard that
 * (`03-database/tables.md` §1.1).
 *
 * The quota count reads across the organization through the second, read-only
 * `workspaces_org_read` policy, which is why `app.organization_id` must be set
 * too. Both settings are established by `withTenant`.
 *
 * ── Quota ────────────────────────────────────────────────────────────────────
 * "Application check inside the creating transaction + advisory lock on
 * `organization_id` to close the race" (`03-database/tables.md` §"Invariants
 * that cannot be enforced declaratively"). The lock is taken BEFORE the count;
 * taking it after would leave exactly the race it exists to close.
 */

import type { DomainEvent, EventPublisher, Transaction } from '@contentos/contracts';
import type {
  AuditActorKind,
  AuditContext,
  AuditWriter,
  NewAuditRecord,
} from '@contentos/security';
import { secureId } from '@contentos/security';

import {
  workspaceArchived,
  workspaceCreated,
  workspaceDeletionRequested,
  workspaceReactivated,
  workspaceSuspended,
  type WorkspaceEventContext,
} from './events.js';
import {
  assertWorkspaceTransitionAllowed,
  DELETION_WINDOW_DAYS,
  isWorkspaceStatus,
  QUOTA_COUNTING_STATUSES,
  resolveWorkspaceTarget,
  restoresPreviousWorkspaceStatus,
  WORKSPACE_INITIAL_STATUS,
  WorkspaceError,
  type WorkspaceStatus,
  type WorkspaceTransition,
} from './lifecycle.js';
import { DEFAULT_WORKSPACE_SETTINGS, WORKSPACE_SETTINGS_KEYS } from './settings.js';

/**
 * The executable transaction shape.
 *
 * Declared here rather than shared with the Organizations service because that
 * module is frozen for this increment; the two are structurally identical and
 * worth unifying when both can be touched.
 */
export interface WorkspaceExecutor extends Transaction {
  query<T>(sql: string, params?: readonly unknown[]): Promise<readonly T[]>;
}

export interface WorkspaceAuditActor {
  readonly id: string;
  readonly kind: AuditActorKind;
}

export const WORKSPACE_AUDIT_ACTIONS = {
  provision: 'workspace.created',
  suspend: 'workspace.suspended',
  reactivate: 'workspace.reactivated',
  archive: 'workspace.archived',
  restore: 'workspace.restored',
  request_deletion: 'workspace.deletion_requested',
  cancel_deletion: 'workspace.deletion_cancelled',
} as const satisfies Readonly<Record<WorkspaceTransition | 'provision', string>>;

export type WorkspaceAuditAction =
  (typeof WORKSPACE_AUDIT_ACTIONS)[keyof typeof WORKSPACE_AUDIT_ACTIONS];

/** Which recorded action a restoring transition reads its prior status from. */
const RESTORE_SOURCE_ACTION: Readonly<Partial<Record<WorkspaceTransition, string>>> = {
  reactivate: WORKSPACE_AUDIT_ACTIONS.suspend,
  restore: WORKSPACE_AUDIT_ACTIONS.archive,
  cancel_deletion: WORKSPACE_AUDIT_ACTIONS.request_deletion,
};

export const WORKSPACE_PREVIOUS_STATUS_KEY = 'previousStatus';

/** Only an `active` organization may gain workspaces. */
export const WORKSPACE_CREATING_ORG_STATUS = 'active';

/**
 * Transaction-scoped advisory lock on the organization.
 *
 * `_xact_` matters: the lock releases on commit OR rollback, so a failed
 * provision cannot strand it and no explicit unlock path exists to forget.
 * `13-event-platform/observability.md` names "a stuck advisory lock" as a real
 * failure mode; a session-scoped lock here would be one waiting to happen.
 *
 * Two int keys rather than one bigint, with the first naming the purpose, so
 * this lock cannot collide with an unrelated advisory lock elsewhere in the
 * platform. Both are computed by PostgreSQL from text, so there is no magic
 * number to keep in sync.
 */
const ADVISORY_LOCK_SQL = `SELECT pg_advisory_xact_lock(hashtext('workspace_quota'), hashtext($1))`;

const TENANT_CONTEXT_SQL = `SELECT current_setting('app.tenant_id', true) AS tenant_id`;

const SELECT_ORGANIZATION_SQL = `
  SELECT id, status, plan_limits
    FROM organizations
   WHERE id = $1 AND deleted_at IS NULL`;

/**
 * `archived` and `pending_deletion` do not consume quota, so they are excluded
 * by the status filter rather than by a comment.
 */
const COUNT_WORKSPACES_SQL = `
  SELECT count(*)::int AS count
    FROM workspaces
   WHERE organization_id = $1
     AND deleted_at IS NULL
     AND status = ANY($2)`;

const INSERT_WORKSPACE_SQL = `
  INSERT INTO workspaces (id, organization_id, slug, name, status, settings, created_by, updated_by)
  VALUES ($1,$2,$3,$4,$5,$6,$7,$7)
  RETURNING id, version`;

const INSERT_ADMIN_SQL = `
  INSERT INTO workspace_memberships (
    tenant_id, organization_id, user_id, role, status, created_by, updated_by
  ) VALUES ($1,$2,$3,'workspace_admin','active',$4,$4)
  RETURNING id`;

/** Append-only: no version, no updated_*, and UPDATE/DELETE are revoked at the role level. */
const INSERT_SETTINGS_HISTORY_SQL = `
  INSERT INTO workspace_settings_history (
    tenant_id, organization_id, changed_keys, before, after, changed_by
  ) VALUES ($1,$2,$3,$4,$5,$6)
  RETURNING id`;

const SELECT_WORKSPACE_SQL = `
  SELECT id, organization_id, slug, name, status, version
    FROM workspaces
   WHERE id = $1 AND deleted_at IS NULL`;

const UPDATE_STATUS_SQL = `
  UPDATE workspaces
     SET status = $1, version = version + 1, updated_at = now(), updated_by = $2
   WHERE id = $3 AND version = $4 AND deleted_at IS NULL
  RETURNING version`;

const SELECT_RECORDED_PREVIOUS_SQL = `
  SELECT context -> 'detail' ->> '${WORKSPACE_PREVIOUS_STATUS_KEY}' AS previous_status
    FROM audit_log
   WHERE tenant_id = $1
     AND target_kind = 'workspace'
     AND target_id = $2
     AND action = $3
   ORDER BY created_at DESC, id DESC
   LIMIT 1`;

const UNIQUE_VIOLATION = '23505';

/** `workspaces` has one unique key per organization — the slug. */
function isSlugConflict(error: unknown): boolean {
  if (typeof error !== 'object' || error === null) return false;
  const record = error as Record<string, unknown>;
  if (record['code'] !== UNIQUE_VIOLATION) return false;
  const constraint = record['constraint'];
  return typeof constraint !== 'string' || constraint.includes('slug');
}

/**
 * The workspace cap from the `PlanLimits` projection.
 *
 * `null` means Commerce has not supplied one yet — `organizations.plan_limits`
 * defaults to `{}` and is "applied, never authored, here". Refusing every
 * creation until `SubscriptionChanged` arrives would make an organization
 * unusable at the exact moment it is created, and the organization's own first
 * workspace is provisioned by a consumer of `OrganizationCreated`. So an absent
 * cap does not enforce; it is Commerce's to set.
 */
function maxWorkspacesOf(planLimits: unknown): number | null {
  if (typeof planLimits !== 'object' || planLimits === null) return null;
  const value = (planLimits as Record<string, unknown>)['maxWorkspaces'];
  return typeof value === 'number' && Number.isInteger(value) && value >= 0 ? value : null;
}

export interface WorkspaceServiceOptions {
  readonly publisher: EventPublisher;
  readonly audit: AuditWriter;
  readonly now?: () => Date;
  readonly newEventId?: () => string;
  /** Counts refusals, for the `quota_rejections_total` signal. */
  readonly onQuotaRejected?: (organizationId: string) => void;
}

export interface ProvisionWorkspaceCommand {
  /**
   * The workspace id, which IS the tenant id. It must equal the `tenantId` the
   * transaction was opened with — see this module's header.
   */
  readonly workspaceId: string;
  readonly organizationId: string;
  readonly slug: string;
  readonly name: string;
  /** Becomes the first `workspace_admin`, active immediately. */
  readonly adminUserId: string;
  readonly actor: WorkspaceAuditActor;
  readonly correlationId: string;
  readonly causationId?: string | null;
  readonly reason?: string;
  readonly context?: AuditContext;
}

export interface ProvisionedWorkspace {
  readonly workspaceId: string;
  readonly organizationId: string;
  readonly adminMembershipId: string;
  readonly adminUserId: string;
  readonly settingsHistoryId: string;
  readonly status: WorkspaceStatus;
  readonly version: number;
}

export interface TransitionWorkspaceCommand {
  readonly workspaceId: string;
  readonly transition: WorkspaceTransition;
  readonly reason: string;
  readonly actor: WorkspaceAuditActor;
  readonly correlationId: string;
  readonly causationId?: string | null;
  readonly expectedVersion?: number;
  readonly context?: AuditContext;
}

export interface WorkspaceTransitionResult {
  readonly workspaceId: string;
  readonly organizationId: string;
  readonly previousStatus: WorkspaceStatus;
  readonly status: WorkspaceStatus;
  readonly version: number;
  /** Never null: every workspace transition has an event in the contract. */
  readonly event: DomainEvent<unknown>;
}

export interface WorkspaceQuota {
  readonly organizationId: string;
  readonly used: number;
  /** Null when Commerce has not projected a cap. */
  readonly limit: number | null;
  readonly allowed: boolean;
}

export interface WorkspaceService {
  provision(
    tx: WorkspaceExecutor,
    command: ProvisionWorkspaceCommand,
  ): Promise<ProvisionedWorkspace>;
  transition(
    tx: WorkspaceExecutor,
    command: TransitionWorkspaceCommand,
  ): Promise<WorkspaceTransitionResult>;
  /** The quota reading, under the same advisory lock provisioning takes. */
  checkQuota(tx: WorkspaceExecutor, organizationId: string): Promise<WorkspaceQuota>;
}

const EMPTY_CONTEXT: AuditContext = {
  ipAddress: null,
  userAgent: null,
  sessionId: null,
  stepUpSatisfied: false,
};

function withDetail(base: AuditContext, detail: Readonly<Record<string, string>>): AuditContext {
  return { ...base, detail: { ...base.detail, ...detail } };
}

interface WorkspaceStateRow {
  readonly id: string;
  readonly organization_id: string;
  readonly slug: string;
  readonly name: string;
  readonly status: string;
  readonly version: number;
}

export function createWorkspaceService(options: WorkspaceServiceOptions): WorkspaceService {
  const now = options.now ?? ((): Date => new Date());
  const newEventId = options.newEventId ?? secureId;
  const { publisher, audit } = options;

  function auditEntry(
    workspaceId: string,
    organizationId: string,
    action: WorkspaceAuditAction,
    command: {
      readonly actor: WorkspaceAuditActor;
      readonly correlationId: string;
      readonly context?: AuditContext;
    },
    reason: string,
    detail: Readonly<Record<string, string>>,
  ): NewAuditRecord {
    return {
      // The workspace IS the tenant, so this record is visible to exactly the
      // tenant-scoped reads that should see it.
      tenantId: workspaceId,
      organizationId,
      actorId: command.actor.id,
      actorKind: command.actor.kind,
      correlationId: command.correlationId,
      action,
      target: { kind: 'workspace', id: workspaceId, tenantId: workspaceId },
      result: 'success',
      reason,
      context: withDetail(command.context ?? EMPTY_CONTEXT, detail),
    };
  }

  /**
   * Fail with a NAMED error when the transaction is not running under the
   * workspace being created.
   *
   * RLS would reject the insert anyway; this turns an opaque policy violation
   * into the actual mistake, which is that `withTenant` was opened with the
   * wrong id.
   */
  async function assertTenantContext(tx: WorkspaceExecutor, workspaceId: string): Promise<void> {
    const rows = await tx.query<{ tenant_id: string | null }>(TENANT_CONTEXT_SQL);
    const current = rows[0]?.tenant_id ?? null;
    if (current !== null && current !== workspaceId) {
      throw new WorkspaceError(
        'TenantContextMismatch',
        `The transaction is running under tenant '${current}' but would create workspace '${workspaceId}'. workspaces.id IS tenant_id; open the transaction with the workspace id.`,
      );
    }
  }

  async function readQuota(
    tx: WorkspaceExecutor,
    organizationId: string,
  ): Promise<{ quota: WorkspaceQuota; organizationStatus: string }> {
    const orgRows = await tx.query<{ id: string; status: string; plan_limits: unknown }>(
      SELECT_ORGANIZATION_SQL,
      [organizationId],
    );
    const organization = orgRows[0];
    if (organization === undefined) {
      throw new WorkspaceError(
        'OrganizationNotFound',
        `Organization '${organizationId}' does not exist.`,
      );
    }

    const limit = maxWorkspacesOf(organization.plan_limits);
    const countRows = await tx.query<{ count: number }>(COUNT_WORKSPACES_SQL, [
      organizationId,
      [...QUOTA_COUNTING_STATUSES],
    ]);
    const used = countRows[0]?.count ?? 0;

    return {
      organizationStatus: organization.status,
      quota: { organizationId, used, limit, allowed: limit === null || used < limit },
    };
  }

  async function readRecordedPreviousStatus(
    tx: WorkspaceExecutor,
    workspaceId: string,
    transition: WorkspaceTransition,
  ): Promise<string | null> {
    const action = RESTORE_SOURCE_ACTION[transition];
    if (action === undefined) return null;

    const rows = await tx.query<{ previous_status: string | null }>(SELECT_RECORDED_PREVIOUS_SQL, [
      workspaceId,
      workspaceId,
      action,
    ]);
    return rows[0]?.previous_status ?? null;
  }

  function eventFor(
    command: TransitionWorkspaceCommand,
    from: WorkspaceStatus,
    ctx: WorkspaceEventContext,
  ): DomainEvent<unknown> {
    const workspaceId = command.workspaceId;
    switch (command.transition) {
      case 'suspend':
        return workspaceSuspended(ctx, {
          workspaceId,
          reason: command.reason,
          suspendedAt: ctx.occurredAt,
        });
      case 'archive':
        return workspaceArchived(ctx, { workspaceId, archivedBy: command.actor.id });
      case 'request_deletion':
        return workspaceDeletionRequested(ctx, {
          workspaceId,
          purgeAfter: new Date(
            Date.parse(ctx.occurredAt) + DELETION_WINDOW_DAYS * 24 * 60 * 60 * 1000,
          ).toISOString(),
        });
      // All three restoring transitions publish `WorkspaceReactivated`. Its
      // contract payload — `{ workspaceId, previousStatus }` — is shaped for
      // exactly this, and it is the only event in the contract that fits.
      // `previousStatus` is the status moved AWAY from, matching how
      // `WorkspaceRenamed` uses `previousName`; the restored status is read
      // from the row, since envelopes carry identifiers rather than state.
      case 'reactivate':
      case 'restore':
      case 'cancel_deletion':
        return workspaceReactivated(ctx, { workspaceId, previousStatus: from });
    }
  }

  return {
    async checkQuota(tx, organizationId) {
      await tx.query(ADVISORY_LOCK_SQL, [organizationId]);
      const { quota } = await readQuota(tx, organizationId);
      return quota;
    },

    async provision(tx, command) {
      await assertTenantContext(tx, command.workspaceId);

      // FIRST. Two concurrent provisions for one organization serialise here,
      // so the count below cannot be read by both before either inserts.
      await tx.query(ADVISORY_LOCK_SQL, [command.organizationId]);

      const { quota, organizationStatus } = await readQuota(tx, command.organizationId);

      // Rule 4, plus organizations rule 13: `past_due` is "full function ...
      // no new workspaces", and suspended / pending_closure / closed are
      // further along the same road. Only `active` may gain a workspace.
      if (organizationStatus !== WORKSPACE_CREATING_ORG_STATUS) {
        throw new WorkspaceError(
          'OrganizationNotActive',
          `Organization '${command.organizationId}' is '${organizationStatus}'; only an '${WORKSPACE_CREATING_ORG_STATUS}' organization may gain workspaces.`,
        );
      }

      if (!quota.allowed) {
        options.onQuotaRejected?.(command.organizationId);
        throw new WorkspaceError(
          'QuotaExceeded',
          `Organization '${command.organizationId}' uses ${String(quota.used)} of ${String(quota.limit)} workspaces; creating another would exceed the plan quota.`,
        );
      }

      const settings = DEFAULT_WORKSPACE_SETTINGS;

      let version: number;
      try {
        const rows = await tx.query<{ id: string; version: number }>(INSERT_WORKSPACE_SQL, [
          command.workspaceId,
          command.organizationId,
          command.slug,
          command.name,
          WORKSPACE_INITIAL_STATUS,
          JSON.stringify(settings),
          command.actor.id,
        ]);
        const row = rows[0];
        if (row === undefined) {
          throw new WorkspaceError(
            'WorkspaceNotFound',
            'The workspace insert returned no row; provisioning cannot continue.',
          );
        }
        version = row.version;
      } catch (error: unknown) {
        // The UNIQUE (organization_id, slug) constraint decides a race, not a
        // prior SELECT that both racers would pass.
        if (isSlugConflict(error)) {
          throw new WorkspaceError(
            'SlugAlreadyTaken',
            `Workspace slug '${command.slug}' is already taken in organization '${command.organizationId}'; slugs are unique per organization and immutable.`,
          );
        }
        throw error;
      }

      // The first admin, ACTIVE immediately — a workspace with no active
      // administrator is unadministrable and its data unreachable by normal
      // paths, which is what last-owner protection exists to prevent.
      const adminRows = await tx.query<{ id: string }>(INSERT_ADMIN_SQL, [
        command.workspaceId,
        command.organizationId,
        command.adminUserId,
        command.actor.id,
      ]);
      const adminMembershipId = adminRows[0]?.id;
      if (adminMembershipId === undefined) {
        throw new WorkspaceError(
          'WorkspaceNotFound',
          'The first admin membership insert returned no row; the workspace would have no administrator.',
        );
      }

      // The initial settings layer, recorded in the append-only history so the
      // workspace's configuration has a first entry rather than appearing to
      // have been configured by nobody.
      const historyRows = await tx.query<{ id: string }>(INSERT_SETTINGS_HISTORY_SQL, [
        command.workspaceId,
        command.organizationId,
        [...WORKSPACE_SETTINGS_KEYS],
        JSON.stringify({}),
        JSON.stringify(settings),
        command.actor.id,
      ]);
      const settingsHistoryId = historyRows[0]?.id;
      if (settingsHistoryId === undefined) {
        throw new WorkspaceError(
          'WorkspaceNotFound',
          'The initial settings history insert returned no row.',
        );
      }

      await audit.record(
        tx,
        auditEntry(
          command.workspaceId,
          command.organizationId,
          WORKSPACE_AUDIT_ACTIONS.provision,
          command,
          command.reason ?? 'Workspace provisioned.',
          {
            status: WORKSPACE_INITIAL_STATUS,
            adminUserId: command.adminUserId,
            quotaUsed: String(quota.used),
            quotaLimit: quota.limit === null ? 'unset' : String(quota.limit),
          },
        ),
      );

      await publisher.publish(
        tx,
        workspaceCreated(
          {
            eventId: newEventId(),
            correlationId: command.correlationId,
            causationId: command.causationId ?? null,
            occurredAt: now().toISOString(),
            organizationId: command.organizationId,
          },
          {
            workspaceId: command.workspaceId,
            organizationId: command.organizationId,
            name: command.name,
            slug: command.slug,
            createdBy: command.adminUserId,
          },
        ),
      );

      return {
        workspaceId: command.workspaceId,
        organizationId: command.organizationId,
        adminMembershipId,
        adminUserId: command.adminUserId,
        settingsHistoryId,
        status: WORKSPACE_INITIAL_STATUS,
        version,
      };
    },

    async transition(tx, command) {
      const rows = await tx.query<WorkspaceStateRow>(SELECT_WORKSPACE_SQL, [command.workspaceId]);
      const current = rows[0];
      if (current === undefined) {
        // Cross-workspace access returns 404, never 403.
        throw new WorkspaceError(
          'WorkspaceNotFound',
          `Workspace '${command.workspaceId}' does not exist.`,
        );
      }
      if (!isWorkspaceStatus(current.status)) {
        throw new WorkspaceError(
          'InvalidTransition',
          `Workspace '${command.workspaceId}' holds unknown status '${current.status}'.`,
        );
      }

      const from: WorkspaceStatus = current.status;
      const organizationId = current.organization_id;
      assertWorkspaceTransitionAllowed(from, command.transition);

      const recordedPrevious = restoresPreviousWorkspaceStatus(command.transition)
        ? await readRecordedPreviousStatus(tx, command.workspaceId, command.transition)
        : null;
      const next = resolveWorkspaceTarget(command.transition, recordedPrevious);

      const expectedVersion = command.expectedVersion ?? current.version;
      const updated = await tx.query<{ version: number }>(UPDATE_STATUS_SQL, [
        next,
        command.actor.id,
        command.workspaceId,
        expectedVersion,
      ]);
      const version = updated[0]?.version;
      if (version === undefined) {
        throw new WorkspaceError(
          'ConcurrentModification',
          `Workspace '${command.workspaceId}' changed under this transaction; expected version ${String(expectedVersion)}.`,
        );
      }

      await audit.record(
        tx,
        auditEntry(
          command.workspaceId,
          organizationId,
          WORKSPACE_AUDIT_ACTIONS[command.transition],
          command,
          command.reason,
          {
            [WORKSPACE_PREVIOUS_STATUS_KEY]: from,
            status: next,
            transition: command.transition,
          },
        ),
      );

      const ctx: WorkspaceEventContext = {
        eventId: newEventId(),
        correlationId: command.correlationId,
        causationId: command.causationId ?? null,
        occurredAt: now().toISOString(),
        organizationId,
      };
      // Unlike organization transitions, EVERY workspace transition has an
      // event in the contract, so there is no audited-but-silent path here.
      const event = eventFor(command, from, ctx);
      await publisher.publish(tx, event);

      return {
        workspaceId: command.workspaceId,
        organizationId,
        previousStatus: from,
        status: next,
        version,
        event,
      };
    },
  };
}
