"""initial schema

Revision ID: a88a7a785659
Revises: 
Create Date: 2026-07-03 19:29:03.430321
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88a7a785659'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('topic_node', sa.String(length=512), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website', 'topic_node', name='uq_memory_site_topic')
    )
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_website'), ['website'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('audience', sa.String(length=512), nullable=True),
    sa.Column('tone', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('council_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_project_id'), ['project_id'], unique=False)

    op.create_table('debate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debate_project_id'), ['project_id'], unique=False)

    op.create_table('decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('point', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_project_id'), ['project_id'], unique=False)

    op.create_table('outline',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('elements', sa.JSON(), nullable=True),
    sa.Column('schema_hooks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outline_project_id'), ['project_id'], unique=False)

    op.create_table('research',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('serp', sa.JSON(), nullable=True),
    sa.Column('headings', sa.JSON(), nullable=True),
    sa.Column('paa', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_project_id'), ['project_id'], unique=False)

    op.create_table('usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_run_id'), ['run_id'], unique=False)

    op.create_table('draft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('outline_id', sa.String(length=36), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['outline.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_outline_id'), ['outline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_project_id'), ['project_id'], unique=False)

    op.create_table('claim',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_draft_id'), ['draft_id'], unique=False)

    op.create_table('internal_link',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('anchor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internal_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internal_link_draft_id'), ['draft_id'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('seo', sa.Float(), nullable=False),
    sa.Column('aeo', sa.Float(), nullable=False),
    sa.Column('geo', sa.Float(), nullable=False),
    sa.Column('heo', sa.Float(), nullable=False),
    sa.Column('eeat', sa.Float(), nullable=False),
    sa.Column('fact', sa.Float(), nullable=False),
    sa.Column('spam', sa.Float(), nullable=False),
    sa.Column('originality', sa.Float(), nullable=False),
    sa.Column('publish', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_draft_id'), ['draft_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_draft_id'))

    op.drop_table('score')
    with op.batch_alter_table('internal_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internal_link_draft_id'))

    op.drop_table('internal_link')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_draft_id'))

    op.drop_table('claim')
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_project_id'))
        batch_op.drop_index(batch_op.f('ix_draft_outline_id'))

    op.drop_table('draft')
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_run_id'))
        batch_op.drop_index(batch_op.f('ix_usage_project_id'))

    op.drop_table('usage')
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_project_id'))

    op.drop_table('research')
    with op.batch_alter_table('outline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outline_project_id'))

    op.drop_table('outline')
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_project_id'))

    op.drop_table('decision')
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debate_project_id'))

    op.drop_table('debate')
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_project_id'))

    op.drop_table('agent_run')
    op.drop_table('project')
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_website'))

    op.drop_table('memory')
    # ### end Alembic commands ###
